name: Unit Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, npm te
        run: |
          cd shared
          npm i
          npm run build
          cd dist
          npm link
          cd ../../server
          npm link engraved-shared
          npm i
          npm test
        env:
          CI: true
