name: Unit Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, npm test
        run: |
          cd shared
          npm i
          npm test
          npm run build
          cd ../client
          npm i
          npm run build
          cd ../server
          npm i
          npm test
        env:
          CI: true
